### ISSUE TITLE
Some suggestions and feedback on the use of dog models

### ISSUE THREAD

**Issue by 1450143535** [wongnata/PlayerDogModel_Plus#47] opened 2024-09-29 06:52 UTC
First of all, thank you very much for updating and supporting this dog model, because I really liked this dog model in v49 version。However, during the process of playing with friends, it was found that when the player turned into a dog model, the first person perspective screen would constantly shake, affecting the player's operations when searching for things and fighting monsters; Secondly, when players pick up items, the size of the items is slightly small, as well as the height of the dog model's perspective. We hope the author can adopt these issues, and also hope that the author can appropriately reduce the height of the dog model's perspective in later updates to fit the gameplay of the dog model

**Comment by wongnata** [comment] 2024-09-29 09:59
Thanks for the feedback! I'm happy to look into these things! 

To help me look into this further, could you
- Attach a screenshot showing the item sizing issue
- Attach a screenshot showing the height issue 
- Attach the mod hash you've been using with your friends

Thanks for playing!

**Comment by 1450143535** [comment] 2024-09-29 10:38
May I ask if this mod hash refers to our mod data log?

**Comment by wongnata** [comment] 2024-09-29 22:26
Oh sorry I could have been more clear! I just need to know what other mods you have installed!

If you use a modpack with your friends, you can let me know the modpack name

If you use r2modman, you can export a code for your mod list and paste that for me
![image](https://github.com/user-attachments/assets/5f9bd63a-5417-433c-85b5-4a81eb11eea7)
![image](https://github.com/user-attachments/assets/9cc8c747-1054-4baa-9a8c-e554abe0a9dd)

If you do neither of these, just let me know the names of the other mods you use and the version of this mod you're using!

**Comment by 1450143535** [comment] 2024-09-30 02:52
First of all, thank you very much for your careful explanation. The following two pictures show the first perspective height when I am in the employee form and the first perspective height when I am in the dog form during normal gameplay. After switching models, the perspective did not change in height. 
![first person camera](https://github.com/user-attachments/assets/bc8e3096-1d83-4518-9480-b268a719368d)
![first dog camera](https://github.com/user-attachments/assets/506ebf22-bad7-49d2-b680-0e38bbf99bdf)
The following notebook contains all the mod versions in the integration package that I personally created！
[mod version.txt](https://github.com/user-attachments/files/17183208/mod.version.txt)

**Comment by 1450143535** [comment] 2024-09-30 03:00
First of all, thank you very much for your careful explanation. The following two pictures show the first perspective height when I am in the employee form and the first perspective height when I am in the dog form during normal gameplay. 
![first person camera](https://github.com/user-attachments/assets/3e0b5660-d2c9-4bce-aae8-c167fc94c1d3)
After switching models, the perspective did not change in height. 
![first dog camera](https://github.com/user-attachments/assets/1b1e7090-cabd-414f-a8c7-8cb5f1b8e6d0)
The following notebook contains all the modules versions in the integration package that I have created myself. Some modules use older versions, and my idea is that older versions may have fewer bugs and be relatively stable. I have tried other versions of the puppy model before, but they all had screen shaking and no changes in height
[mod version.txt](https://github.com/user-attachments/files/17183259/mod.version.txt)

**Comment by wongnata** [comment] 2024-09-30 04:15
Thanks so much for all the detailed information! I'll get this set up so I can look into it further! 

Some initial thoughts based on the mod list and the screenshots are:

- It looks like when in dog mode, the camera height does not get adjusted _but_ the item anchor (where the model holds items) _does_ get updated, so that's why the held items look so much smaller. I think that if we're able to figure out why the camera height isn't getting adjusted, that will fix the item size issue too!
- It looks like your mod list includes ModelReplacementAPI which I believe the original mod said conflicts with PlayerDogModel, so I'll have to see if that might be causing the camera issue or the shaking issue! If you are curious, it might be worth trying to disable ModelReplacementAPI  (and whichever mods use it) and see if that results in any changes! I will be trying this too

**Comment by 1450143535** [comment] 2024-09-30 04:23
Thank you for your hard work. I have tried to create a new integration package that does not include the ModelReplacement API. However, when I am in the puppy model, the screen still shakes. Please study and test it more to bring more exciting versions for the future

**Comment by wongnata** [comment] 2024-09-30 04:59
Good news! I was able to track down the incompatibility for the camera height / item size issue! It seems like it's an issue with CruiserImproved. I would recommend disabling that mod for now, and I would still recommend uninstalling ModelReplacementAPI since I don't think your mod list is using it for anything! I can look into why CruiserImproved was causing this camera issue.

Here's a video showing your mod list running without CruiserImproved and ModelReplacementAPI:
https://github.com/user-attachments/assets/f2f96122-a3ec-4147-b97e-9ddbae3b407d

Please let me know if this helps and if the screen shake issue continues!

**Comment by 1450143535** [comment] 2024-09-30 05:17
Thank you very much for your investigation and analysis. After retesting and deleting the mod, I have indeed resolved the issues of screen shake and first person perspective height. The CruiserImproved mod does indeed affect the first person perspective of players in the puppy model. I hope the author can conduct more in-depth analysis and debugging of the mod in the future to adapt to it

**Comment by wongnata** [comment] 2024-09-30 05:19
Another update, I figured out why CruiserImproved is causing this issue: it's because they have a [patch which resets the camera position every frame](https://github.com/digger1213/CruiserImproved/blob/6159533fee9c5748ef667067a9cbb66ba5fa6237/source/Patches/PlayerController.cs#L36). 

To use CruiserImproved and PlayerDogModel_Plus at the same time, you should update both of these config settings in DiggC.CruiserImproved.cfg: 

- Allow Leaning = false
- Seat Boost Scale = 0

So my recommendation right now is:

- Uninstall ModelReplacementAPI
- Update the config settings for CruiserImproved
  - Allow Leaning = false
  - Seat Boost Scale = 0

What I can do in the meantime is submit a PR to CruiserImproved so that it will only adjust the camera position when you are in a vehicle! That would prevent the conflict with PlayerDogModel_Plus. I will post the link to the PR when it is available and then hopefully the author for CruiserImproved will test and approve it!

Thanks for your help!

**Comment by 1450143535** [comment] 2024-09-30 05:23
Okay, we look forward to receiving updates and adjustment notifications from you in the future

**Comment by wongnata** [comment] 2024-09-30 05:51
Raised a PR to fix this issue in CruiserImproved [here](https://github.com/digger1213/CruiserImproved/pull/18)!

**Comment by wongnata** [comment] 2024-09-30 06:10
[Rejected the PR](https://github.com/digger1213/CruiserImproved/pull/18) since the author confirmed that they have their own solution planned for a future update.

![image](https://github.com/user-attachments/assets/84147906-be26-4731-9735-0fe42906d70b)

In the meantime, please use the workaround provided above and watch for a future update to CruiserImproved!

Closing this issue.

**Closed** 2024-09-30 06:10 UTC
Labels: invalid
